### ISSUE TITLE
Filter orders by date created and date updated

### ISSUE THREAD

**Issue by bradydan** [print-trail/api-spec#1]
- [x] On `getOrder`, the response should include date created and last updated (timestamps)
- [x] On `searchOrders`, add a query parameter to filter orders by date created and last updated (timestamps)

**Comment by judgej** [comment]
Filter documented here: https://print-trail.github.io/api-spec/#operation/searchOrders

**Comment by judgej** [comment]
Also includes filtering by the order status or list of statuses.
